# SPDX-License-Identifier: GPL-3.0-or-later
#
# Injects all Arduino-ESP32 framework built-in library include paths into the
# build. PlatformIO's LDF does not propagate framework built-in library headers
# into third-party library compilation (e.g. ESPAsyncWebServer needs FS.h,
# WiFi.h, etc.). Adding libraries/*/src mirrors what the Arduino IDE does.
Import("env")
import os, glob, gzip

# ── Embed web UI into the firmware ────────────────────────────────────────
# The whole UI is ~12 KB gzipped, so it lives in the app binary as PROGMEM
# blobs instead of a separate LittleFS image. One firmware.bin = one upload;
# no `pio run -t uploadfs`, no FS partition / mount / FS-OTA to go wrong.
# Regenerated every build so editing data/*.html just needs a rebuild.
def _embed_web_assets():
    proj = env.subst("$PROJECT_DIR")
    data_dir = os.path.join(proj, "data")
    out_path = os.path.join(proj, "src", "web_assets.h")
    # name -> (source file, C identifier)
    assets = [
        ("index.html", "WEB_INDEX_HTML"),
        ("style.css",  "WEB_STYLE_CSS"),
    ]
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// AUTO-GENERATED by extra_script.py — do not edit by hand.",
        "// gzip-compressed web UI, served from PROGMEM (Content-Encoding: gzip).",
        "#pragma once",
        "#include <pgmspace.h>",
        "#include <stddef.h>",
        "",
    ]
    for fname, ident in assets:
        src = os.path.join(data_dir, fname)
        with open(src, "rb") as f:
            gz = gzip.compress(f.read(), 9)
        body = ",".join(str(b) for b in gz)
        lines.append("static const uint8_t %s_GZ[] PROGMEM = {%s};" % (ident, body))
        lines.append("static const size_t  %s_GZ_LEN = %d;" % (ident, len(gz)))
        lines.append("")
        print("Embedded %s -> %s_GZ (%d B gzipped)" % (fname, ident, len(gz)))
    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines))

_embed_web_assets()

packages_dir = env.subst("$PROJECT_PACKAGES_DIR")
lib_glob = os.path.join(packages_dir, "framework-arduinoespressif32", "libraries", "*", "src")

added = []
for lib_src in glob.glob(lib_glob):
    lib_src = lib_src.replace("\\", "/")
    env.Append(CPPPATH=[lib_src])
    added.append(os.path.basename(os.path.dirname(lib_src)))

if added:
    print("Injected framework libs:", ", ".join(sorted(added)))
else:
    print("WARNING: no framework libraries found under", lib_glob)
