#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Regenerate components/web/include/web_assets.h from the source web UI in
# data/. Replaces the old PlatformIO extra_script.py (dropped in the ESP-IDF
# port). The ESP-IDF CMake does NOT run this automatically, so after editing
# data/index.html or data/style.css you must run:
#
#     python tools/gen_web_assets.py
#
# then rebuild (idf.py build). Each asset is gzip-compressed (level 9, fixed
# mtime for reproducible output) and emitted as a PROGMEM byte array plus a
# matching _LEN, served with Content-Encoding: gzip by web_server.cpp.

import gzip
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "components", "web", "include", "web_assets.h")

# (source file, C symbol base) — order preserved in the header.
ASSETS = [
    ("data/index.html", "WEB_INDEX_HTML_GZ"),
    ("data/style.css",  "WEB_STYLE_CSS_GZ"),
]

def gz(path):
    with open(os.path.join(ROOT, path), "rb") as f:
        raw = f.read()
    # mtime=0 → deterministic output (no spurious diffs on rebuild).
    return gzip.compress(raw, compresslevel=9, mtime=0)

def emit_array(name, data):
    body = ",".join(str(b) for b in data)
    return (f"static const uint8_t {name}[] PROGMEM = {{{body}}};\n"
            f"static const size_t  {name}_LEN = {len(data)};\n")

def main():
    parts = [
        "// SPDX-License-Identifier: GPL-3.0-or-later\n",
        "// AUTO-GENERATED by tools/gen_web_assets.py — do not edit by hand.\n",
        "// gzip-compressed web UI, served from PROGMEM (Content-Encoding: gzip).\n",
        "#pragma once\n",
        "#include <pgmspace.h>\n",
        "#include <stddef.h>\n",
        "\n",
    ]
    for path, name in ASSETS:
        data = gz(path)
        parts.append(emit_array(name, data))
        parts.append("\n")
        print(f"{path}: {os.path.getsize(os.path.join(ROOT, path))} -> {len(data)} B gz ({name})")
    with open(OUT, "w", newline="\n") as f:
        f.write("".join(parts).rstrip("\n") + "\n")
    print(f"wrote {OUT}")

if __name__ == "__main__":
    main()
